ratings:
  All:
    description: ""
    classType: default
  Tier 1:
    description: "Extraordinary Food and service. A treat."
    classType: success
  Tier 2:
    description: "Memorable experience, worthy of return visits."
    classType: default
  Tier 3:
    description: "Acceptable value but in no hurry to return."
    classType: warning
  Tier 4:
    description: "Substandard value or execution."
    classType: warning
  Solid:
    description: "Pleasing food or experience. Worth a trip."
    classType: default
  Mediocre:
    description: "Average, unworthy of special attention."
    classType: warning
  Hellscape:
    description: "Avoid at all costs."
    classType: danger

tiers:
  Somerville:
    Davis Sq:
      Spoke: "Tier 1"
      Posto: "Tier 3"
      The Table at Season To Taste: "Tier 3"
      Painted Burro: "Solid"
      Dave’s Fresh Pasta: "Solid"
      3 Little figs: "Solid"
      Qingdao Garden: "Solid"
      Cafe Barada: "Mediocre"
      Hana Sushi: "Mediocre"
      Blue Shirt Cafe: "Hellscape"
      Diesel: "Mediocre"
      Five Horses Tavern: "Mediocre"
      Redbones: "Mediocre"
      Saloon: "Mediocre"
      Urban Hearth: "Hellscape"
      Out of the Blue: "Hellscape"
      Orleans: "Hellscape"
      Foundry on Elm: "Hellscape"
      Sugidama: "Mediocre"
      Meju: "Mediocre"

    Porter Sq:
      Guilia: "Tier 1"
      Forage: "Tier 3"
      Shepard: "Tier 3"
      Elephant walk: "Tier 4"
      Gran Gusto: "Tier 4"
      Cambridge common: "Mediocre"
      Trattoria pulcinella: "Mediocre"
      Christopher's: "Hellscape"
      Tavern in the Square: "Hellscape"
      Abbey: "Hellscape"
      Baraka Cafe: "Hellscape"
      Temple bar: "Hellscape"


    Union Sq:
      Backbar: "Tier 3"
      Bronwyn: "Tier 3"
      Journeyman: "Tier 4"
      Casa B: "Tier 4"

    Other:
      La Brasa: "Tier 2"
      Sarma: "Tier 1"
      Fat Hen: "Tier 2"
      Kirkland Tap and Trotter: "Tier 3"
      Dali: "Tier 3"
      TW Food: "Hellscape"
      Kebab Factory: "Mediocre"
      Highland Kitchen: "Mediocre"

  Cambridge:
    Inman Sq:
      Puritan: "Tier 2"
      BisQ: "Tier 3"
      Bergamot: "Tier 3"
      East Coast Grill: "Tier 3"
      Ole: "Tier 4"
      Loyal Nine: "Tier 4"
      Punjhabi Dhaba: "Solid"
      Trina's: "Mediocre"
      City Girl Cafe: "Mediocre"
      All Star Sandwich: "Mediocre"
      All Star Pizza: "Mediocre"
      
      Tupelo: "Hellscape"
      Clover: "Hellscape"
      Ginger Exchange: "Hellscape"
      Midwest Grill: "Hellscape"

    Harvard Sq:
      Alden and Harlow: "Tier 1"
      Parsnip: "Tier 3"
      Russell House Tavern: "Tier 3"
      Harvest: "Tier 4"
      Henrietta's Table: "Tier 4"
      Tasty Burger: "Solid"
      Grafton Street Pub: "Hellscape"
      Border Cafe: "Hellscape"
      The Maharaja: "Solid"

    Central Sq:
      Cafe Sushi: "Tier 1"
      Craigie on Main: "Tier 2"
      Salts: "Tier 3"
      Little Donkey: "Tier 3"
      Viale: "Tier 3"
      Garden at the Cellar: "Tier 3"
      Central Kitchen: "Tier 4"
      Waypoint: "Tier 4"
      Cellar: "Solid"
      Flour: "Solid"
      Green Street: "Mediocre"
      Miracle of Science: "Mediocre"
      Cafe Rangzen: "Hellscape"
      Pepper Sky: "Hellscape"
      Asmara: "Hellscape"
      Cuchi Cuchi: "Hellscape"

    Kendall Sq:
      Oleana: "Tier 1"
      Belly: "Tier 3"
      Bondir: "Tier 3"
      Blue room: "Tier 4"
      Commonwealth: "Tier 4"
      Fuji: "Tier 3"
      Area Four Cambridge: "Tier 3"
      Catalyst: "Tier 4"
      Helmand: "Tier 4"
      Dante: "Tier 4"
      Emmas: "Mediocre"
      Firebrand Saints: "Mediocre"
      Mulan: "Solid"
      Koreana: "Solid"
      Desfina: "Solid"
      Similans: "Mediocre"
      Lord Hobo: "Mediocre"
      Area Four: "Mediocre"
      Acituna: "Mediocre"
      Tatte: "Mediocre"
      Evoo: "Hellscape"
      Za: "Hellscape"
      Abigail's: "Hellscape"
      Kika Tapas: "Hellscape"
      Meadhall: "Hellscape"
      Squeaky Beaker: "Hellscape"
      ArtBar: "Hellscape"
      Bambara: "Hellscape"
      Second St.: "Hellscape"
      Friendly Toast: "Hellscape"
      Cambridge Brewing Company: "Hellscape"

  Boston:
    Downtown:
      O Ya: "Tier 1"

    Back Bay:
      L’espalier: "Tier 3"
      Atlantic Fish Company: "Tier 3"

    Seaport:
      Row 34: "Tier 1"
      Menton: "Tier 2"

    Kenmore Sq:
      Island Creek Oyster Bar: "Tier 2"

    South End:
      Toro: "Tier 1"
      Butcher Shop: "Tier 2"
      Oishii Boston: "Tier 2"
      Mistral: "Tier 2"

    Park Street:
      No. 9 park: "Tier 3"
      Silvertone: "Hellscape"

    Fenway:
      Citizen Public House: "Solid"
      Sweet cheeks: "Mediocre"
